### ISSUE TITLE
Käännetyssä versiossa changes ei näytä muuta kuin alkuperäisen suomenkielisen

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1557]
In GitLab by @vesal on Oct 13, 2019, 17:15

Jos käännetyssä versiossa suomenkielinen ei ole muuttunut ja muuttaa käännöstä,
niin se näkyy keltaisena, mutta kun klikkaa Changes, niin näkyy vain alkuperäinen suomenkielinen, ei käännös.

**Comment by saviit** [comment]
Näyttäisi olevan korjattu, kts. <https://tim.jyu.fi/view/users/viitanen-sami/issuet/1557/ankkalinna/en-US>. 

![changes](https://github.com/TIM-JYU/TIM/assets/46485327/2a898294-0de1-43f3-a0d7-ef4db5fee72a)

Oranssi lukumerkintä peittää keltaisen Changes-alueen, jos oranssin klikkaa pois niin myöskään keltainen ei näy ennen kuin ottaa kappale-editorilla täpän pois kohdasta `Mark as read`.

Suljetaan korjattuna.
