### ISSUE TITLE
Customize tim sivulle tagejä joihin voi hypätä ja joita voi helposti kopioida ihmisille tiedoksi

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1784]
In GitLab by @vesal on Apr 23, 2020, 12:57

Esimerkikäyttötapus: 

Käyttäjä kysyy: Mistä saan käyttäjätunnukseni?

Opettaja: https://tim.jyu.fi/settings#userid

**Comment by sijualle** [comment]
Toteutettu #3316
