### ISSUE TITLE
Keltaisen klikkaaminen käännöksessä näyttää alkuperäisen kielen tekstin

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#1817]
In GitLab by @vesal on May 17, 2020, 19:18

Varmaan jos käännöksessä haluaa katsoa diff, pitäisi näyttää käännöksen ero edelliseen
lukemiseen.

**Comment by saviit** [comment]
Duplikaatti kortista #1557. Tämä on myös korjattu.
