### ISSUE TITLE
Usean sivun käännösdokumentin luominen kerrallaan

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2119]
In GitLab by @roeyskoe on Dec 19, 2020, 15:51

Nykyisellään sivujen käännösdokumenttien luominen on äärimmäisen työlästä, mikäli niitä pitää luoda usealle eri sivulle.

Kansionäkymän managessa voisi olla mahdollisuus luoda kansion jokaiselle dokumentille käännössivu, sekä asettaa jokaiselle jo olemassa olevalle dokumentille kieli, sillä sellaista niillä ei oletuksena ole.
Käyttöliittymän puolesta samantyylinen ratkaisu kuin käyttöoikeuksien määrityksessä voisi olla hyvin toimiva. Ensin asetettaisiin kieli jolle halutaan luoda käännös. Tämän jälkeen aukeaa lista kansion (ja miksei myös alikansioiden) dokumenteista, joille voitaisiin antaa uusi nimi tällä äsken asetetulla kielellä. Oletettavasti käännösdokumentteja kuitenkin luodaan ainoastaan yksi kieli kerrallaan.

**Comment by saviit** [comment]
Dokumenttien kääntäminen TIMissä on muuttunut TIMTra-projektin myötä merkittävästi. Nykyisen tilanteen valossa en näe  tarpeeksi vahvoja perusteita tämän kortin vaatimuksille.

Suljen tämän kortin ei suunniteltuna.
