### ISSUE TITLE
Kahden samankielisen käännöksen luomisen yrittäminen aiheuttaa virheen

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2120]
In GitLab by @roeyskoe on Dec 19, 2020, 16:35

Käännösdokumentit näyttävät aiheuttavan hyvin erikoisia ongelmia, jos alkuperäiselle dokumentille ei ole asetettu kieltä.

Jos "kielettömälle" dokumentille luodaan käännös, katoaa alkuperäinen dokumentti näkyvistä, ellei alkuperäiseen mennä suoran linkin kautta.
Lisäksi jos alkuperäiselle yritetään asettaa kieltä, jolla sille on jo luotu käännösdokumentti, saadaan palvelinvirhe.

Eli esimerkiksi:
1. Luodaan dokumentti (voi olla luotu aiemminkin)
2. Luodaan tälle dokumentille käännös, alkuperäisen dokumentin kielikenttä jätetään tyhjäksi.
3. Automaattisesti siirrytään view-näkymässä luotuun käännökseen, oikeassa yläkulmassa ei näy kielivaihtoehtoja.
4. Siirrytään takaisin manageen, kielien kohdalla näkyy ainoastaan tämä juuri äsken luotu kieli.
5. Siirrytään alkuperäisen dokumentin manageen, vaikka pyyhkimällä osoitepalkista kielivaihtoehto, manageen ilmestyy näkyviin myös tämä alkuperäinen kieletön dokumentti.
6. Jos tälle kielettömälle dokumentille yrittää nyt antaa saman kielen kuin millä sille on jo luotu käännös, saadaan "Something went wrong..."-viesti.

**Comment by saviit** [comment]
Käännöksiä ei voi enää luoda dokumentista, jolle ei ole asetettu kielikoodia. Suljetaan korjattuna.
