### ISSUE TITLE
Jos on lazy-komponentti jossa ei ole stem yms, niin ei näy mitään eikä aktivoidu

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2163]
In GitLab by @vesal on Feb 19, 2021, 08:55

Esim jos laittaa videokomponentille GeoGebra linkin
mutta ei laita header, footer tms, niin lazy-tilassa ei näy mitään.
Sitten kun komponenttien määrä kasvaa niin yhtäkkiä komponentti häviääkin
kun määrän kasvu muuttaa sen lazyksi.

Eli koskee ainakin videopluginia, mutta pitää tutkia voiko muillakin käydä vastaavasti.

**Comment by sijualle** [comment]
Kattelin tuota läpi, toistaiseksi vain showVideo/showImage on sellaiset pluginit joissa ei tule yhtään mitään aktivoitavaa kohtaa jos ei ole laitettu otsikko tms tekstejä. Sen sijaan joissain plugineissa (esim imagex) tulee kyllä aktivoitava elementti, mutta sitä ei juuri tunnista aktivoitavaksi tehtäväksi (pelkkä tyhjä raami ilman mitään "open plugin" tms tekstiä)

https://tim.jyu.fi/view/users/sijualle/kokeiluja/lazyt

Testailen vielä muutamaa pluginia ennen kuin laitan mr
