### ISSUE TITLE
Kirjanmerkkien historia paisuttaa levyn käyttöä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2287]
In GitLab by @Smibu on Jun 1, 2021, 15:33

Kirjanmerkit nykyään tallennetaan dokumenttiin. Aina kun kirjanmerkit muuttuvat (mm. kun käyttäjä menee johonkin dokumenttiin, jolloin se menee "Last read" -listaan), dokumentin muokkaushistoria kasvaa, kuten muillakin dokumenteilla.

Katsoin juuri devs02-koneella skriptillä, kuinka suuri kirjanmerkkidokumentteihin liittyvä historia on yhteensä.

Kirjanmerkkitiedostojen määrä:

* Kansiossa `tim_files/docs`: 11 071 590 tiedostoa/kansiota
* Kansiossa `tim_files/pars`: 8 879 774 tiedostoa/kansiota
* yhteensä 19 951 364 tiedostoa/kansiota

Kaikkien dokumenttitiedostojen määrä:

* Kansiossa `tim_files/docs`: 24 940 119 tiedostoa/kansiota
* Kansiossa `tim_files/pars`: 22 876 749 tiedostoa/kansiota
* yhteensä 47 816 868 tiedostoa/kansiota

(Luvut laskettu Pythonin `glob.iglob('/polku/kansioon/**/**', recursive=True)`-kutsun perusteella.)

Eli kirjanmerkkitiedostot ovat **42% kaikista TIMin dokumenttitiedostoista**.

Kirjanmerkeille ei tarvitsisi tallentaa mitään historiaa. Lähinnä 2 mahdollisuutta tulee mieleen:

1) jotenkin merkataan, että kirjanmerkkidokumenteille ei tallennu historiaa
2) siirretään kirjanmerkit tietokantaan

Mun suosikki on tapa 2, koska:

* Se on helpompi toteuttaa.
  * Tavassa 1 pitäisi olla jokin mekanismi merkata dokumentti historiattomaksi ja muokkailla dokumentin tallentelukoodia sopivasti. Se on hankalampaa kuin saattaisi luulla, koska lohkon tallennuksessa luodaan aina uusi lohkoversiotiedosto ja jätetään vanhat olemaan. Historiattomalle dokumentille pitäisi siis aina poistaa vanhat lohkoversiotiedostot muokkauksen yhteydessä, tai jollakin muulla mekanismilla poistaa ne säännöllisin väliajoin.
  * Tapa 2 taas ei vaadi muuta kuin että päivitetään kirjanmerkkikoodi niin, että yritetään ensisijaisesti ladata
kirjanmerkit tietokannasta ja jos niitä ei löydy sieltä, niin sitten kirjanmerkkidokumentista kuten nykyään. Tallennus muutetaan tallentamaan aina tietokantaan. Sitten vähitellen voidaan skriptillä poistaa sellaiset kirjanmerkkidokumentit, jotka ovat siirtyneet tietokantaan. Ja miksei skripti, joka siirtää kaikki loputkin käyttäjät.
* Kun kirjanmerkit ovat tietokannassa (luultavasti ihan useraccount-taulun sarakkeessa), niin kirjanmerkit saadaan ladattua muiden käyttäjätietojen mukana, eli kirjanmerkkejä ei tarvitse haeskella mistään eri paikasta.

**Comment by dezhidki** [comment]
Vanhojen bookmarkien poistoa nyt kokeiltu timdevs02:ssa seuraavasti:

1. Ensin pakotetaan kirjanmerkkien siirtoa kaikille käyttäjille. Shellissa ensin pakotettu kaikille bookmarkin siirtoa:

    ```py
    >>> for u in User.query:
    ...   try:
    ...     f = u.get_personal_folder()
    ...     bm_doc = f.get_document("Bookmarks")
    ...     if not bm_doc:
    ...       continue
    ...     u.bookmarks.save_bookmarks()
    ...   except Exception as e:
    ...     print(f"{u.name}: {e}")
    ...
    xxx: Personal usergroup for user xxx was not found!
    >>> db.session.commit()
    >>>
    ```

2. Sen jälkeen ajettu kirjanmerkkien poistoa: `./r flask item cleanup-bookmark-docs --no-dry-run --prompt-before-commit`

   Tämä löysi noin 10000 kirjanmerkkidokumenttia, jotka nyt olen poistamassa devs02:ssa testiksi. Poistin aluksi noin 1200 käyttämätöntä kirjanmerkkidokumenttia, ja se vapautti noin 3G tilaa. Tämä on sinänsä ihan järkevä luku, koska kirjanmerkkidokumenteilla on yleensä erittäin suuri historia (katso kortin alkuperäinen viesti, jossa mukana Mikan tilastoja).

Pistin kirjanmerkkien poiston ajamaan devs02:lle, näillä näkymin sillä menee noin 10 h tehdä täydellinen siivous. Katson, tuleeko siitä vielä jotain virheitä. Jos ei, rupean ajamaan saman poiston tuotannossa (mahdollisesti pienissä ryppäissä).

**Comment by vesal** [comment]
>     kirjanmerkkidokumenttia, ja se vapautti noin 3G tilaa. Tämä on sinänsä ihan järkevä luku, koska kirjanmerkkidokumenteilla on yleensä
>     erittäin suuri historia (katso kortin alkuperäinen viesti, jossa mukana Mikan tilastoja).

Olisikos järkeä että joillekin dokumneteille voisi sanoa ettei ole historiaa
lainkaan, tai historian koon.  Varmaan kirjanmerkeillä riittäisi aika pieni
historian koko?

**Comment by dezhidki** [comment]
> Olisikos järkeä että joillekin dokumneteille voisi sanoa ettei ole historiaa
> lainkaan, tai historian koon.  Varmaan kirjanmerkeillä riittäisi aika pieni
> historian koko?

Mika totesi tämän kortin alkuperäisessä viestissä, että käytännössä sellaisen toteuttaminen vaatii niin monta muutosta, että ei ollut järkeä toteuttaa kirjanmerkkejä varten. Olen samaa mieltä hänen kanssaan, etenkin kun nykyään kirjanmerkkien historia toimii, vaikka kirjanmerkit menevät tietokantaan (koska Mika teki jo sen vaihtoehdon).

Tästä kortista siis jäi vain vanhojen kirjanmerkkidokumenttien migraatio, jonka hoidan nyt loppuun. Käytännössä tämä migraatio koskee vain niitä, jotka eivät ole kirjautuneet TIMiin kertaakaan kesän 2021 jälkeen. Aktiivisilla käyttäjilla kirjanmerkit ovat jo siirretty (paitsi että Bookmarks-dokumentti saattaa olla olemassa, mutta sitä TIM ei enää käytä heillä ollenkaan).

**Comment by dezhidki** [comment]
Tarkistin nyt timdevs02:ssa ajetun siivouksen, ja se vapautti yhteensä noin 10000 kirjanmerkkidokumenttia:

```
[@timdevs02 deleted]$ du -sh pars docs
7.9G    pars
11G     docs
```` 

(tämä siis on backup-kansio, johon kopioitiin poistetut dokumentit). Normaaleja dokumentteja tällöin jäi:

```
[dezhidki@timdevs02 tim_files]$ du -sh docs pars
17G     docs
22G     pars
```

Eli siis noin 32 % tilasta saatiin vapautettua sen jälkeen, kun siirrettiin kirjanmerkit (ml. luettujen dokumenttien historia) kantaan. En laskenut tietokannan tilatarvetta, mutta tietokannan pakkauksen ja yksinkertaisen historian tallennustavan takia se kyllä vie vähemmän tilaa kuin pakkaamattomat JSON-tiedostot.

Aloitan siirtoprosessin seuraavasti tuotannossa:

1. Siirrän loppujen vanhojen käyttäjien kirjanmerkit tietokantaan [aiemmin mainitulla komennolla](https://github.com/TIM-JYU/TIM/issues/2287#issuecomment-1175105698)
2. Teen ylimääräisen tietokantadumpin varulta
3. Ajan bookmarkien siivostua ensin kuiva-ajona (eli ei talleneta muutoksia kantaan) arvioidakseen siivouksen kestoa
4. Teen todellisen siivokusen joko erissä tai kaikki kerrallaan riippuen siivouksen vaikutuksesta TIMin nopeuteen

**Comment by dezhidki** [comment]
Tämä nyt saatettu loppuun, yhteensä on siivottu 10894 kirjanmerkkidokumenttia. Tietokannan pakattu koko ei muuttunut merkittävästi; tämä johtuu todennäköisesti siitä, että suurella osalla käyttäjistä kirjanmerkkiasetukset olivat hyvin samankaltaiset tai muuten pienet. Lisäksi 10k+ tietokantarivien poisto kevensi jonkin verran tietokantaa.

Jätän vielä poistettujen kirjanmerkkidokumenttien kansion (`tim_files/deleted`) meille vähintään kesäksi sen varalta, jos huomataan joitain ongelmia. Tämä kortti itsessään on hoidettu loppuun, eli käyttämättömät kirjanmerkkidokumentit vapautettu. Koodiin vielä jäi vanhojen kirjanmerkkidokumenttien migraatiokoodi talteen, mutta se voi ihan hyvin olla siinä toistaiseksi. Laitan kyseiseen koodin merkinnän, että sen voi poistaa myöhemmin käyttämättömyyden takia.

Kortin olennainen juttu on käsitelty, joten laitan tämän kiinni.

**Comment by vesal** [comment]
Kiitti, iso homma.
