### ISSUE TITLE
Dokumenttityylin ottaminen käyttöön URL-argumentilla

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2343]
Nykyiset dokumenttityylit voidaan ottaa käyttöön vain Customize TIMista tai dokumenttiasetuksista. Olisi hyvää, jos dokumenttityylejä voisi ottaa käyttöön väliaikaisesti myös URL-parametrina.

Esimerkiksi:

https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/koti?styles=official/dia-mini
https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/koti?styles=user/blue-dark-light,user/isompi-fontti

**Comment by dezhidki** [comment]
Nykyään onnistuu tyylidokumenteilla (#2990)

**Comment by vesal** [comment]
> Nykyään onnistuu tyylidokumenteilla (#2990)

Onko tuosta esimerkkiä tai ohjetta jossakin miten
tiedosto laitetaan URLissa?

**Comment by dezhidki** [comment]
Löytyy kyllä Sass:n ohjeista, johon viitataan [tyylidokumenttien laadintaohjeissa](https://tim.jyu.fi/view/tim/ohjeita/styles#tyylin-muokkaus). Laitoin samalla nyt esimerkin `@import`in käytöstä niissä

https://tim.jyu.fi/view/tim/ohjeita/styles#toisen-tyylitiedoston-import

**Comment by vesal** [comment]
Tuo ei ollut ihan sama asia, mitä tarkoitin.  Eli tarkoin että
voisi tehdä "maistiaisia" esim kurssin sivuista tyyliin:

https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/koti?styles=official/dia-mini
https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/koti?styles=user/blue-dark-light,user/isompi-fontti

**Comment by dezhidki** [comment]
Okei, tulkitsin kortin otsikon sitten väärin :)

Avasin kortin takaisin ja tarkensin otsikkoa sekä kuvausta

**Comment by dezhidki** [comment]
Nykyään tuettu [`themes`](https://tim.jyu.fi/view/tim/ohjeita/dokumentin-asetukset#themes-url)-asetuksella
