### ISSUE TITLE
Kielivalintaan oikeus

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2474]
In GitLab by @vesal on Dec 21, 2021, 12:15

Tuli toivomus että kun valintakokeet tehdään monelle kielelle, niin pitää etukäteen
valita millä kielellä tekee ja sitten ei muita kieliä saa käyttöönsä.

Alkeellinen versio olisi että tehdään kieliversiot kopioiksi ja annetaan silloin oikeudet,
mutta tuon voisi rakentaa paremmin tuohon sisään

**Comment by saviit** [comment]
Suljetaan toteutettuna/vanhentuneena.
