### ISSUE TITLE
MCQ ei toimi käännösdokumenteissa oikein

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2589]
Esimerkiksi MCQ:n explanation jää alkuperäiselle kielelle, vaikka se käännetään. Lisäksi samat matikkaongelmat kuin #341.

Toistaiseksi korjauksena lienee, että `mcq` ja `mmcq` korvataan `mcq2` ja `mmcq2` -plugineilla.

**Comment by saviit** [comment]
Plugineja `mcq` ja `mmcq` [ei ole enää käytössä](https://tim.jyu.fi/view/tim/TIM-ohjeet#truefalse-tyyppiset-kysymykset).
QST-plugin on korvannut nämä, vanhoissa dokumenteissa olevat mcq2/mmcq2-pluginit muunnetaan qst-plugineiksi lennossa (kts. esim. #1226).

Käsin testattuna MCQ/MMCQ-käännösversiot toimivat myös nykyään oikein. Ongelmana on edelleen se, että käännösversiossa ei saa olla määrityksiä attribuuteille `trueText` ja `falseText`. Nämä on ilmeisesti kovakoodattuina englannin kielelle.

Koska QST on korvannut mcq/mmcq/mmcq2 -pluginit, tähän ei kannata enää käyttää resursseja. Materiaalin laatijat/ylläpitäjät voivat päivittää materiaalinsa käyttämään QST:tä, mikäli mcq/mmcq aiheuttaa ongelmia.

Suljetaan ratkaistuna.
