### ISSUE TITLE
Alueen aloituslohkon muokkaaminen käännösdokumentissa rikkoo sivun

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2616]
Jos tekee collapsible-alueen ja avaa sen otsikon käännösdokumentissa, tulee tallentaessa

```
polyfills.a034473465063700.js?l=en-US:1 Unhandled Promise rejection: area name mismatch 1: undefined !== test ; Zone: <root> ; Task: Promise.then ; Value: Error: area name mismatch 1: undefined !== test
```

**Comment by saviit** [comment]
En saa tätä enää toistettua:

[Testidokumentti 1](https://tim.jyu.fi/view/users/viitanen-sami/issuet/2616)
[Testidokumentti 2](https://tim.jyu.fi/view/users/viitanen-sami/issuet/2616_2)

Tämä on siis oletettavasti korjattu.

**Comment by saviit** [comment]
Suljetaan korjattuna.
