### ISSUE TITLE
Oletusvelppiryhmän luonti ei onnistu jos dokumentilla ei ole omistajia

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2618]
In GitLab by @sijualle on May 27, 2022, 18:06

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/service/timApp/velp/velp.py", line 761, in create_default_velp_group_route
    user_group = doc.block.owners[0]
IndexError: list index out of range
```

**Comment by saviit** [comment]
En saanut tätä toistettua, muistatko @sijualle missä tilanteessa tämä tuli? Vastaava tilanne syntyy, jos yrittää luoda 'Document'-valinnalla luoda velp ryhmiä dokumentille silloin, kun dokumentilla ei ole owner-oikeuksia, mutta se tapahtuu `velp.py`:n _create_velp_group_route_-metodissa (rivi 650).

**Comment by dezhidki** [comment]
Vaikka sen ei saa toistettua, ongelma johtuu samasta syystä, eli

https://github.com/TIM-JYU/TIM/blob/65e06c37cc98d4f47985c6be019f9f7b17bb1fe1/timApp/velp/velp.py#L775

puuttu tarkistus, että onko dokumentissa omistajaa. Tämän voisi korjata nyt samalla #3093:ssa, koska korjaus olisi ihan samanlainen.

**Comment by saviit** [comment]
Joo, tämä olikin vähän mielessä. Laitan nyt alkuun tuohonkin RouteExceptionin. Mitäs mahdollisisa ongelmia voisi aiheutua siitä, jos kaivettaisiin dokumentin omistaja dokumentin sisältävän kansion oikeuksista? Ajattelisin, että kansion omistaja => kansiossa olevan dokumentin omistaja (paitsi erityistapauksissa).

**Comment by dezhidki** [comment]
Nopeasti tulee mieleen, että kansiollakaan ei ole omistajaa. Mutta sinänsä mielestäni järkevää olisi, että siitä tulisi vain selkeä näkyvä virhe käyttäjälle. Tämä niin, koska käytännössä vain adminit (ja jokin vanha TIM-koodi) voi saada aikaan tilanteen, jossa omistajaa ei ole. Peruskäyttäjän ei pitäisi saada tätä aikaan, koska omistaja ei voi poistaa itsensä omistajista, ja manage-tasoinen ei voi poistaa omistajat. Jos peruskäyttäjä voi saada aikaan omistamattoman dokumentin, se pitäisi tutkia ja korjata.

Eli siis jos dokumentissa ei ole omistajaa, siitä riittäisi mielestäni joku ilmoitus, jolloin käyttäjä ilmoittaa siitä eteenpäin.

**Comment by saviit** [comment]
Tämä nyt korjattu PR:ssä #3093. Käyttäjälle annetaan virheilmoitus `showMessageDialog`lla, jos yritetään luoda velp-ryhmää dokumentille, jolla ei ole omistajaa. Tämä pätee sekä 'normaaleille' että oletusvelppiryhmille.
