### ISSUE TITLE
QST  pisteiden pyöristys

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2621]
In GitLab by @vesal on May 30, 2022, 21:57

QST summapisteet voivat olla omituisia, esim TKT 2022 kokeessa

    -5.55111512312578e-17

joka tulee kun sopivasti lasketaan yhteen 0.2 ja -0.2 

https://tim.jyu.fi/teacher/valintakoe/tkt/2022k/tehtavat/tehtava2#t22b

**Comment by ajlakanen** [comment]
Onkos tämä jo korjattu?

**Comment by dezhidki** [comment]
Hei, hyvä että kysyit! Nykyään pisteiden laskussa otetaan huomioon liukulukujen pyöristysepätarkkuudet. Tämä oli korjattu hiljattain Python-päivitysten yhteydessä (d5136e5592daaa1d794d71577998c0635bcfd05d):

https://github.com/TIM-JYU/TIM/blob/master/timApp/answer/answers.py#L165-L166

Suljen tämän siis toteutetuksi
