### ISSUE TITLE
Velp-ryhmien poisto

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2627]
In GitLab by @sijualle on May 31, 2022, 17:01

Tehtyjä velp-ryhmiä ei voi poistaa.

Velp-ryhmään liittyvän dokumentin voi poistaa velpin manage-linkin kautta, jolloin velppi siirtyy roskikseen. Tällöin tosin velppiryhmä jää silti kummittelemaan velp menuun. Nämä "pehmeästi poistetut" velp-ryhmät voisi piilottaa näkyvistä tuolta velp-menusta. Tarvittaessa voisi myös tarkistaa ettei velp-ryhmään kuulu yhtään velppiä ennen kuin se poistetaan.

**Comment by saviit** [comment]
Suljen tämän toteutettuna (PR:ssä #3099).
Velpryhmään kuuluvat velpit eivät estä ryhmän poistamista; jos poistettavaan ryhmään kuuluu vielä velppejä, annetaan varoitus ja listaus niistä. Henkilökohtaista tai dokumentin oletusryhmää ei voi poistaa (ne ovat pysyviä).
