### ISSUE TITLE
Velp menun tai sen Select välilehden koko ei muutu velp-lappujen mukaan

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#2647]
In GitLab by @saviit on Jun 16, 2022, 15:19

Velp menun Select-välilehdellä näytettävät velp-laput/templatet eivät vaikuta Velp menu-ikkunan kokoon odotetusti.

Syy lienee jotakuinkin seuraava:
- velp-laput ovat velp-window komponentteja, joiden kooksi tulee 0 sekä pysty- että vaakasuunnassa
- lappujen visuaaliset elementit asuvat velp-window -komponentin sisällä --> selain ei osaa renderoida parentia oikeassa koossa koska velp-window:n koko on 0

Velp-window-komponenttien koon voi määrätä toki css:llä, mutta en ole toistaiseksi ehtinyt kunnolla kokeilla, onnistuuko niiden asemointi tismalleen kuten niiden sisältämien visuaalisten elementtien. Jos tämä onnistuu, sen pitäisi ratkaista ongelma pääosin. Lisäksi tietysti pitää huolehtia siitä, että alueelle annetaan jokin järkevä maksimikoko, jonka jälkeen velp-lappujen aluetta aletaan scrollata.

**Comment by saviit** [comment]
Ratkaistu PR:ssä #3086 ja #3090
