### ISSUE TITLE
Velp menun kaikki elementit eivät mahdu näytölle

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3080]
Velp menun kaikki elementit eivät välttämättä mahdu näytölle:

1. pieni pystyresoluutio (< 800 px)
2. käyttöliittymän tekstin ja/tai elementtien kokoa skaalattu suuremmaksi joko käyttöjärjestelmän asetuksista tai selaimen asetuksista

Tällä hetkellä aukotonta ratkaisua ei näyttäisi olevan ilman, että Velp menun UI rakennetaan melko lailla uusiksi. Suurimpia ongelmia ovat uusien velppien luominen ja olemassaolevien editointi, sillä velpin editoimisikkuna asettuu editoitavan velpin yläreunasta alkaen: etenkin tallentamis-/keskeytyspainikkeet jäävät usein ruudun ulkopuolelle jos velppejä on paljon ja editoidaan listassa alempana olevaa velppiä. 

Alueen scrollaaminen ei ole ratkaisu, sillä silloin velp-listaa ei pysty irrottamaan alueesta (tai ikkuna kyllä irtoaa, mutta jää kuitenkin pyörimään scrollattavan alueen sisälle).

Haarassa <https://github.com/TIM-JYU/TIM/tree/velp-scroll-areas> on nyt hahmoteltu ja tiivistetty velp menua aika reilustikin pienemmille resoluutioille: tämä on testattavissa timdevsissa esim. dokumentissa <https://timdevs01-4.it.jyu.fi/teacher/users/viitanen-sami/tests/velptest/velps>. Tällä hetkellä 800px pystyresoluutiolla pitäisi mahtua uuden velpin tekeminen kokonaan näytölle, kun käyttöjärjestelmässä skaalaus 100% (eli ei skaalausta), 125% ja isommat rikkovat edelleen tämän.

Tähän liittyen: <https://stackoverflow.com/questions/61434568/windows-10-scaling-default-above-100-causing-website-sizing-issues>

**Comment by vesal** [comment]
Yksi mahdollisuusolisi että jos resoluutio ei riitä, niin nostetaan tuota
sinistä luontialuetta
ylemmäksi koska sinne jäävää tavaraa ei enää tarvita.
Ihannetapauksessa isommal näytöllä tuo scrollatava alue kasvaisi niin,
että scrollaus jäisi minimiin.

**Comment by saviit** [comment]
Ratkaistu PR:sä #3086

**Comment by vesal** [comment]
jos isonnan velp-menu aletta, niin kaikki velpit eivät
mahdu näyttöön.   itse asiassa isonnettua aluetta ei käytetä hyödyksi.
Jos irroitan velpit, en voi sitä dialogia suurentaa.

dia-kokeessa en jostakin syystä näe kuin omia velppejäni?
niitähän oli tehty lohkokohtaisesti?

**Comment by dezhidki** [comment]
> jos isonnan velp-menu aletta, niin kaikki velpit eivät
> mahdu näyttöön.   itse asiassa isonnettua aluetta ei käytetä hyödyksi.
> Jos irroitan velpit, en voi sitä dialogia suurentaa.

Itselläni ainakin onnistuu velppilistan koon vaihtaminen (video alla):

[test.webm](https://user-images.githubusercontent.com/5202606/176858348-7c398caf-d33e-4a28-b23c-57120d3c58ca.webm)

Siinä nyt taidetaan käyttää selaimen omaa resizea, ja ainakin Chromessa se menee aina vasempaan alalaitaan.
@saviit: Kokeilitko käyttää `tim-draggable-fixed`:n omaa `resize`-attribuuttia? Eli siis 

https://github.com/TIM-JYU/TIM/blob/0218021746522e21061b06b7ff97b3f04f72c92b/timApp/static/templates/velpSelection.html#L42-L47

kokeilee vaihtaa `resize="true"`, jolloin koon muuttamiseksi käytetään draggablen omia palkkeja. Tosin jos ei toimi, niin en ehkä rupeaisi kovin kauan sen kanssa taistelemaan, koska tuo korjaantuu paremmaksi kun ehtii tehdä AngularJS->Angular siirron tälle.

Laitan tämän kortin auki sen ajaksi, kun testaillet. Voit sitten päättää testin perusteella, mitä tälle kortille tehdään (laitetaanko kiinni tai tehdäänkö vaikka oma kortti tuolle resize hommalle).

> dia-kokeessa en jostakin syystä näe kuin omia velppejäni?
> niitähän oli tehty lohkokohtaisesti?

Sehän taisi olla niin, että tarkistajat tekivät omat henkilökohtaiset velpit eivätkä käyttäneet velppiryhmiä ollenkaan. Esimerkiksi ainoastaan velppiryhmässä `ongt2_5` on yksi velppi nimeltään "OK" (joka näyttää toimivan ja ilmestyvän oikein ainakin itselleni, kun klikkaan tehtävää 2.5). Mutta en rupea syvällisesti menemäät tähän tässä, koska kortti on julkinen.

**Comment by saviit** [comment]
> Kokeilitko käyttää tim-draggable-fixed:n omaa resize-attribuuttia?

En, tuo jäi huomioimatta vielä näissä commiteissa, samaten se itse velp-korttien koon määrittely ja oikea asemointi (kts. #2647). Minäpäs testailen vielä.

Dia-kokeen tarkastajat oli tosiaan tehneet ne velppinsä henkilökohtaisina, minkä takia ne ei näy muille. Jatkoa varten voisi tietty ajatella, että nuo menisi oletuksena dokumentille?

**Comment by saviit** [comment]
> kokeilee vaihtaa resize="true", jolloin koon muuttamiseksi käytetään draggablen omia palkkeja

Draggablen palkit eivät nähtävästi ainakaan velp menun kanssa toimi pystysuunnassa ollenkaan. Nopeasti katsottuna draggablen `moveResize` (jonka pitäisi tuo elementin uusi koko laskea) asettaa elementille koon `height` ja `width` -määreillä. Pienille näytöille sovittamista varten taas monille elementeille on jouduttu nyt laittamaan `min-height`, `max-height`, jne., jotka ehkä ajavat yli noista `moveResize`n asettamista. Velppi-alueen "normaali"-resize (eli css:ssä `resize: vertical` asetus) on nyt sitten puolivälin ratkaisu näihin ennenkuin keksitään fiksumpaa/siirrytään uuteen Angulariin.

Asetin nyt tuolle velppilistalle myös reunuksen kun se on irrotettuna, se ehkä helpottaa huomaamaan tuon resize-kahvan. Velp-listan pitäisi nyt myös olla oletuksena suurempi kun sen irrottaa velp menusta.

**Comment by dezhidki** [comment]
Okei, joo. Uudessa Angular-dialogissa tuo min/max rajat ainakin kunnioitetaan, eli saadaan korjattua kunnolla, kun ehtii siirtää. Mutta mielestäni ainakin näyttää järkevältä; siitä voi ainakin jo laittaa PR.

**Comment by vesal** [comment]
Nyt näkyy Chromessa tuollainen jolla voi velp alueen koko muuttaa.  Mutta iPadissä ei näy ;.(
Voisiko muuten vastaava alueen koon muuttaminen olla siinä Velp groups listassakin?

**Comment by saviit** [comment]
Ratkaistu PR:ssä #3294 ja #3313
