### ISSUE TITLE
Postilistaa pikkuparannuksia

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3146]
https://tim.jyu.fi/view/messagelists/ohj1s22k

Nykyiset jäsenet

- [ ] jos "jäsen" on ryhmä, niin määrä montako tulee ryhmästä
- [ ] jos jäsen on ryhmä, niin nimi linkiksi ryhmään

Muut tarpeelliset:

- [ ] Miten löytää helposti kursille luomansa postilistan?  Kurssilaisten listaan on kotisivulla linkki.
- [ ] #3147
      niin varoitus että tarviiko omaa listaa.  Matikka sanoi että käyttä vasta sitten kun tämä ominaisuus on.
      Eli ko linkki/painike ryhmän sivulle ja ihannetilanteesa myös Sisu-ryhmien taulukoon, koska sinne
      lähes jokainen opettaja joutuu menemään. 
- [ ] ei kuulu suoraan tähän, mutta tuolla em. Sisu-sivulla voisi olla myös joku käänteinen tapa
       laittaa kurssisivu jos sitä ei älyä tehdä kurssin kautta. (toki tämä lukee sivun ohjeissa)

**Comment by dezhidki** [comment]
Suurin osa näistä näyttää jo olevan ViesTIMin kortissa #2296, eli siirtäisin nämä siihen. Ainakin tuo ryhmätaulukon jutut sekä listan luominen ryhmän kautta ovat jo siellä. Eli onko tämä kortti ihan tarpeellinen?

**Comment by vesal** [comment]
Tuon prioriteettia nostaisin että listan saa luotua ryhmän puolelta ja silloin se täyttäisi kysymyksiä
niin valmiiksi kuin mahdollista.  Muuten ehkä ei tarvita tätä jos kaikki on jo tiedossa.

**Comment by dezhidki** [comment]
Tein postiluostan luomisesta ryhmästä oman kortin. Siirrän vielä tuon "Kurssilaisten listaan on kotisivulla linkki." ViesTIM-korttiin.
