### ISSUE TITLE
DIA-mini tyylillä Ohj1-menut ovat läpinäkyviä

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3151]
https://tim.jyu.fi/teacher/kurssit/tie/ohj1/2022s/koti

- menut läpinäkyviä
- ei pääse takaisin settingsiin
- etusivu on aika ahdas

**Comment by saviit** [comment]
Menun sai takaisin normaaliksi asettamalla sivun omissa asetuksissa:

````
``` {settings="" id="F45mGuPhu1OK"}

[...]

themes:
- dia-mini

[...]

css: |!!

[...]

.timMenu {
    z-index: 1000 !important;
}
!!
```
````

**Comment by saviit** [comment]
Hampurilaismenun saa takaisin laittamalla tuonne samaan yllämainittuun

`
tim-sidebar-menu {
    display: inline;
}
`

**Comment by saviit** [comment]
Molemmat edellisistä näyttäisivät toimivan myös preamblen kautta, eli jos lisää preambleen

```
.timMenu {
    z-index: 1000 !important;
}
tim-sidebar-menu { 
    display: inline; 
}
!!
```

niin saa korjattua preamble-menun ja saa sivulle hampurilaisvalikon takaisin, muuttamatta DIA-mini-tyyliä.

Etusivun ahtaudelle ei liene hirveästi muuta tehtävissä kuin jakaa tavaraa useampaan sivuun - tai tehdä kokonaan uusi tyyli. joka jaottelee sisällön leveämmin sivulle (tämä tosin aiheuttanee ongelmia mobiilille).

**Comment by vesal** [comment]
Mutta eikös tuo pitäisi saada että toimii kenellä vaan joka
ottaa ko tyylin köyttän?

**Comment by vesal** [comment]
> Etusivun ahtaudelle ei liene hirveästi muuta tehtävissä kuin jakaa tavaraa
> useampaan sivuun - tai tehdä kokonaan uusi tyyli. joka jaottelee sisällön
> leveämmin sivulle (tämä tosin aiheuttanee ongelmia mobiilille).

Tuo on minusta ahtaampi kuin perustyylin etusivu.
Pienempi fontti tms?

**Comment by saviit** [comment]
> Mutta eikös tuo pitäisi saada että toimii kenellä vaan joka
ottaa ko tyylin köyttän?

Joo no kyllähän se varmaan luonnistuu ihan vain lisäämällä nuo samat tuonne DIA-mini-tyyliin. Se tietysti tarkoittaa, että muuts heijastuu kaikille, joilla se on jo käytössä (tämän takia en suoraan alkanut muokata kys. tyyliä). Testaan vielä tämän.

> Tuo on minusta ahtaampi kuin perustyylin etusivu.
> Pienempi fontti tms?

Molemmissa tyyleissä fonttikoko on 16px ja fonttiperhe sans/sans serif. DIA-tyylissä itse tekstille jäävä alue on kapeampi, ts. sisältökaistaleella on paddingia reilusti. TIMin oletustyylissä ei ole lähes lainkaan paddingia sisältökaistaleessa, joten sisältö levittyy väljemmin.

**Comment by saviit** [comment]
> > Mutta eikös tuo pitäisi saada että toimii kenellä vaan joka
> > ottaa ko tyylin köyttän?
> 
> Joo no kyllähän se varmaan luonnistuu ihan vain lisäämällä nuo samat tuonne DIA-mini-tyyliin. Se tietysti tarkoittaa, että muuts heijastuu kaikille, joilla se on jo käytössä (tämän takia en suoraan alkanut muokata kys. tyyliä). Testaan vielä tämän.

timMenu ja hampurilaismenu korjattu nyt suoraan DIA-mini tyylissä. Hampurilaismenu tosin oli vielä kirjattu itse tyylitiedostoon WIP.

**Comment by dezhidki** [comment]
Menut näyttää olevan korjattu tämän ketjun perusteella, etusivun ahtaus kai jäi. Siirsin tuon ahtauden korttiin #3183, koska siellä on nyt muitakin eri kohtia.

**Comment by vesal** [comment]
> Molemmissa tyyleissä fonttikoko on 16px ja fonttiperhe sans/sans serif. DIA-tyylissä itse tekstille jäävä alue on kapeampi, ts.
> sisältökaistaleella on paddingia reilusti. TIMin oletustyylissä ei ole lähes lainkaan paddingia sisältökaistaleessa, joten sisältö
> levittyy väljemmin.

Olisikohan meillä tuossa DIA-minissä edes tarvetta kaventaa sitä tekstialuetta.
Toiko se jotakin "hyvää"?  Uskaltaisiko sitä ajatella niin, että DIA-mini olisi
tyyli jossa poimitaan vain "fiksuiksi" koetut ominaisuudet tuolta.

Ja Sitten itse DIA on mikä on :-)
