### ISSUE TITLE
Silk.NET ei toimi kunnolla ajokontissa

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3153]
Tällä hetkellä jos TIMiin asentaa uusimman Jypelin (11.2.x), joka käyttää Silk.NETia MonoGamen sijaan, tulee ajokontissa virhe

```
Unhandled exception. System.PlatformNotSupportedException: Couldn't find a suitable window platform. (GlfwPlatform - not applicable, SdlPlatform - not applicable) https://dotnet.github.io/Silk.NET/docs/hlu/troubleshooting.html
   at Silk.NET.Windowing.Window.Create(WindowOptions options)
   at Jypeli.Game.InitWindow()
   at Jypeli.Game..ctor()
   at Jypeli.PhysicsGameBase..ctor(IPhysicsEngine engine)
   at Jypeli.PhysicsGame..ctor()
   at Peli..ctor()
   at Program.<Main>$(String[] args)
```

Katso esim https://timdevs01-2.it.jyu.fi/view/tim/Eri-ohjelmointikielia#punainenympyra.

Ongelma on jotenkin Silk.NETissa, eli se ei nyt tunnista ajokontissa olevaa GLFW + X.11 serveria.

Tämä kuitenkin vaikuttaa nyt vain timdevseihin sekä lokaaleihin koneisiin. Tuotannossa tätä ongelmaa ei nyt joistan syystä ilmesty.

**Comment by dezhidki** [comment]
Jypeli 11.1 ja sen riippuvuudet näyttävät toimivan ajokontissa. Erot:

Jypeli 11.1:

[FontStashSharp](https://www.nuget.org/packages/FontStashSharp/) (>= 1.0.4)
[Silk.NET.Input](https://www.nuget.org/packages/Silk.NET.Input/) (>= 2.12.0)
[Silk.NET.OpenAL](https://www.nuget.org/packages/Silk.NET.OpenAL/) (>= 2.12.0)
[Silk.NET.OpenAL.Soft.Native](https://www.nuget.org/packages/Silk.NET.OpenAL.Soft.Native/) (>= 1.21.1.1)
[Silk.NET.OpenGL](https://www.nuget.org/packages/Silk.NET.OpenGL/) (>= 2.12.0)
[Silk.NET.Windowing](https://www.nuget.org/packages/Silk.NET.Windowing/) (>= 2.12.0)
[SixLabors.ImageSharp](https://www.nuget.org/packages/SixLabors.ImageSharp/) (>= 1.0.4)

Jypeli 11.2:

[FontStashSharp](https://www.nuget.org/packages/FontStashSharp/) (>= 1.0.4)
[Silk.NET.Input](https://www.nuget.org/packages/Silk.NET.Input/) (>= 2.15.0)
[Silk.NET.OpenAL](https://www.nuget.org/packages/Silk.NET.OpenAL/) (>= 2.15.0)
[Silk.NET.OpenAL.Soft.Native](https://www.nuget.org/packages/Silk.NET.OpenAL.Soft.Native/) (>= 1.21.1.1)
[Silk.NET.OpenGL](https://www.nuget.org/packages/Silk.NET.OpenGL/) (>= 2.15.0)
[Silk.NET.Windowing](https://www.nuget.org/packages/Silk.NET.Windowing/) (>= 2.15.0)
[SixLabors.ImageSharp](https://www.nuget.org/packages/SixLabors.ImageSharp/) (>= 2.1.0)

Eli ongelmana on hyvin todennäköisesti Silk.NET. Laitan väliaikaisesti versiolukituksen `11.1.*` Jypelille, jotta tuotantoa ei rikottaisi vahingossa siinä välissä, kun tutkin ongelmaa.

**Comment by dezhidki** [comment]
Nyt on tehty https://github.com/Jypeli-JYU/Jypeli/pull/30, odotellaan sen megetystä sekä version korotusta ennen jatkotoimia. Toistaiseksi tuotannossa on Jypeli 11.1, joka toiminee ihan hyvin demoissa ja tehtävissä.

**Comment by roeyskoe** [comment]
Jypelistä on muutaman minuutin päästä uusi paketti ulkona.

**Comment by dezhidki** [comment]
Jes, timbetalla nyt toimii. Laitan kohta tuotantoon, silloin saattaa tulla 1-2 min "katko" Jypeli-tehtävien ajossa.
