### ISSUE TITLE
addParAbove/addParBelow -painikkeet toimimaan dialogilla

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3158]
Nykyään lohkon lisääminen painikkeella onnistuu, mutta se avaa kokonaisen lohkoeditorin.

Sen lisäksi voisi tarjota vaihtoehdon, joka avaa dialogin (tai dialogeja), jossa kysytään syötettä ja lisätään lohko syötteen perusteella.

Käytttötapaus:

* SUKOL-kokeessa opettajakohtainen sivu, jolla opettaja lisää rekisteröintilomakkeet. Lomake luodaan painikkeella, dialogista kysyttään esim. luokan nimi. Painike tekee opettajadokumenttiin linkin, joka sitten luo dokumentin templatella.

**Comment by vesal** [comment]
tuohon käyttötapauksern voisi harkita myös yhtä sivua,
joka toimii url-makroilla.

Vesa
