### ISSUE TITLE
Saisiko lukulistaan vielä määrät

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3166]
Tuolla

https://tim.jyu.fi/view/messages/tim-messages/2022-09-03-094429032505-Ohj1-Olethan-huomannut-etta-sinulla-ei-viela-tayta-demo-1n-minimit

saa nuo lukijat kivasti, mutta kun noita on niin paljon niin saisiko noihin vielä määrät viereen.

**Comment by dezhidki** [comment]
Lisätty Stats-linkki timMenuun (1bca57eee5c0dc0ac0b8a477ede3f66e52b1e8f5), koska se on nopein tapa toistaiseksi. 

Jatkokehityksenä varmaan luvut voisi näyttää suoraan dokumentissa ilman tarvetta klikata erillistä linkkiä. Tämä kuitenkin lienee vähemmän kriittinen, joten siirrän sen ViesTIMin jatkokehityskorttiin (#2296)
