### ISSUE TITLE
csplugin: Jypeli + save_video kaatuu, jos pelissä on ääniä

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3179]
Minimaalinen esimerkki: 

https://tim.jyu.fi/view/users/dezhidki/tim-tests/test-save-video-crash

```cs
using System;
using System.Collections.Generic;
using Jypeli;
using Jypeli.Assets;
using Jypeli.Controls;
using Jypeli.Widgets;

public class KolmionMetsastys : PhysicsGame
{
    public override void Begin()
    {
        Add(new Explosion(10));
    }
}
```

Virhe:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Jypeli.Audio.OpenAL.OpenAL.Destroy(UInt32 handle)
   at Jypeli.SoundEffect.Finalize()
```

Teen tästä kohta korjauksen Jypeliin, mutta laitan kortin meille seuraamaan Jypelin päivittämistä cspluginissa.

**Comment by dezhidki** [comment]
Laitettu PR: https://github.com/Jypeli-JYU/Jypeli/pull/31

Toistaiseksi varmistaa, että TIMiin laitettavissa peleissä ei ole ääntä aiheuttavia toimintoja (esim. räjähdyksiä).

**Comment by roeyskoe** [comment]
Mergetty Jypeliin ja uusi paketti ihan kohta ulkona.

**Comment by dezhidki** [comment]
Uusin versio (11.3.1) laitettu nyt tuotantoon. Näyttää nyt toimivan oikein. Laitan siis kiinni ratkaistuna.
