### ISSUE TITLE
Supermakrot tai automaatio

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3180]
Tämä on karkea idea tässä vaiheessa.

Tarvittaisiin jonkinlaisia supermakroja vai nimitetäänkö jotakin automaatioksi. 

Selkeimmät pienet ovat luoda preamble yms tiedostoja.

Osin selkeä on myös että luodaan sähköpostilista ryhmälle.  Eli hyvin selkeä sarja toimenpiteitä
joilla saadaan tuo tehtyä.

Hieman monimutkaisempi esimerkki on kurssisivun luominen ja liittäminen sisu-ryhmään.  Tai jopa 
niin, että Sisu ryhmästä lähdetään ja syntyy kotisivu ja postilista.

Koko pienen kurssisivuston tekeminen niin, että on myös yksinkertainen pistelasku. jne.

Hieman eri suuntaan menevä on esim tuo miten tehdää vaikkax-y kuvaaja datasta:

  https://tim.jyu.fi/teacher/kurssit/tie/ohj1/2021s/mailit#runner_o1_m1

Eli yleisesti sanoen hyvin samanlaisten asioiden tuottaminen, jossa on muutama
parametri (tossa viimeisessä se, mikä data on x-akselilla ja mikä y-akselilla ja sitten
sen perusteella luoda kaksi komponenttia oikeilla sisällöillä).

Meillä voi tehdä hirveän paljon erilaisia asioita, mutta niiden tekemiseksi tarvitaan
yleensä meidän apua.  Jos pystyisi aina jonkin asian tehdessään paketoimaan
"supermakroksi", joka tekee sen kaiken ihmisen puolesta.  Silloin seuraavan
käyttäjän ei tarvitse pyytää apua samaan tehtävään.

**Comment by dezhidki** [comment]
Tuo kuulostaa aika läheltä https://github.com/TIM-JYU/TIM/issues/2558, pitäisiköhän ehkä kortit yhdistää?

**Comment by vesal** [comment]
Ainakin niillä on paljon yhteistä.  Tuo graafijuttu (xy) tuossa mulle ei suoraan ole kyse uusien dokumenttien
luomisesta, mutta toki dokumentin sisällä operoimista. Sitä pitäisi sitten miettiä mistä näitä "supermakroja"
sitten löytäisi.  Osa voi olla editorissa (esim tuo xy), mutta esim preamblen luontihan ei ole dokumentin muokkaamista.

**Comment by dezhidki** [comment]
> Osa voi olla editorissa (esim tuo xy)

Sinänsä se onnistuu jo nyt, sillä templateihin saa laittaa yksinkertaiset dialogit (katso esim. [vertaisarvioinnin template](https://github.com/TIM-JYU/TIM/blob/5505914e3edcba7aa366eb07105733678177a1c5/timApp/modules/svn/templates/video/1/Table%20And%20Fields%20by%20macros#L3))

Toki jos sen haluaa monipuolistaa, se voisi ehkä tehdä jotenkin niin, että se myös edistäisi #2558:n ajatusta jostain lomakesyntaksista.

> preamblen luontihan ei ole dokumentin muokkaamista

Näkisin, että yleistä preamblen tekemistä varten olisi oma painike. Sitten jos haluaa esim. tehdä kurssin jostain pohjasta, niin sitä varten olisi tuo #2558:n wizard.

> Sitä pitäisi sitten miettiä mistä näitä "supermakroja"
sitten löytäisi.

Joo, tosin joka tapauksessa ehkä miettisin supermakrojen sijaan JSRunnerin laajentamista, koska meillä on sitä varten jo valmis pohja (JS-skriptaus, mahdollisuus rakentaa API, mahdollisus välittää tieto takaisin TIMille). Eli toteuttamatta #2558:n kannalta on oikeastaan vain rajapinta JSRunneriin sekä varsinaisten operaatioiden toteutus TIMiin.
"Supermakrot" jotenkin viittaavat Jinja-makroihin, joille meillä ei oiken ole mitään pohjaa rakentamaan JSRunnerin tapaista skriptausta. Siksi siis mietinkin kyseisessä kortissa juuri JSRunnerin käyttämistä eikä jonkun uuden syntaksin keksimistä jinja-makrojen päälle.

**Comment by dezhidki** [comment]
Tehty nyt seuraavasti:

* Siiirretty tässä kortissa esitettyjä käyttötapauksia korttiin #2558
* xy-graafin juttu siirretty omaan korttiin (koska se oli mainittu "asian sivusta"): #3182

Eli nyt tämän kortin asiat pitäisi olla jaettuna tarkemmin muihin kortteihin.
