### ISSUE TITLE
Kääntämättömien atomilohkojen sisältö ei näy käännösdokumentissa täydellisesti

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3231]
Katso muokkauksia

https://tim.jyu.fi/manage/kurssit/tie/ohj1/moniste/Ohjelmointi-1

30.10.2022 klo 8 jälkeen.  Atomit hajosivat muokkauksessa ja tämä  teki tosi hankalaksi
en-version ylläpidon.

**Comment by saviit** [comment]
Minimaalinen esimerkki: <https://tim.jyu.fi/view/users/viitanen-sami/testikansio/translation-tests/atomic/en-US>

Tämä syntyi niin, että 

1.	tein ensin kaksi teksilohkoa
2.	käänsin dokumentin en-US
3.	lisäsin kaksi uutta atomista lohkoa ja tarkistin, että kopioituivat käännökseen
4.	palasin muokkaamaan alkuperäisen viimeistä lohkoa
5.	nyt käännösdokumentissa editori näyttää, että uusi teksti pitäisi olla atomisen lohkon sisällä, mutta ei tule näkyviin itse dokumentissa

**Comment by vesal** [comment]
Oliko siis tuo:

       Tämä on käännösdokumentin luomisen jälkeen lisätty atominen lohko.

       public class Atomic 
       {
               public static void Main() 
       .... 

aluksi yksi editoitava yksikkö kun lisäsit sen (atom).  Ja sitten muokkasit sitä ja se hajosi fi puolella
kahdeksi lohkoksi.  Mulle kävi sillä tavalla.  Eli oli paljon lohkoja joissa oli tekstiä ja välissä
ohjelmalohko johon merkkasin ```c#  alkuun ja silloin ne erkaantuivat useammaksi lohkooksi
katketen aina tuon c# kohdalta.

**Comment by saviit** [comment]
> aluksi yksi editoitava yksikkö kun lisäsit sen (atom). Ja sitten muokkasit sitä ja se hajosi fi puolella
> kahdeksi lohkoksi.

Tuo itse asiassa ei hajonnut kahdeksi lohkoksi, vaan koodilohko ja sen yläpuolella ollut teksti olivat alunperinkin kaksi erillistä lohkoa. Mulla oli tuolla siis seuraavasti koodilohko:

````{atom="true}
```c#
public class Atomic
{
...
}
```
````

Sitten kun tuota muokkaa editorilla, niin lisätty teksti tulee kyllä atomisen lohkon eli ````{atom="true"} sisään. Mutta käännösdokumentissa sitä ei näy dokumenttinäkymässä, vaikka editori kyllä sen löytää ja näyttää että se olisi siellä.

**Comment by vesal** [comment]
Kataoppas minkälainen mulla oli siellä
"Kuormitus"-luvussa alunperin ja mitä
sitten muuttui kun muokkasin klo 8 jälkeen.

Ainakin ne tekstit tuli ensin "yhtenä lohkona" mulle
muokattavaksi, mutta jokaisen muokkausken jälkeen
muuttuivat useammaksi "muokkauslohkoksi".

**Comment by saviit** [comment]
> Ainakin ne tekstit tuli ensin "yhtenä lohkona" mulle
> muokattavaksi, mutta jokaisen muokkausken jälkeen
> muuttuivat useammaksi "muokkauslohkoksi".

Joo, eli tämä nykyinen toiminta on se malli, miten sen on (ilmeisesti) ajateltukin toimivan. Tuo johtuu siitä, että takahipsuilla tehty koodilohko aloittaa/luo atomisen uuden lohkon. Tässä on nyt ainakin kolme vaihtoehtoa, miten voisi edetä.

*Vaihtoehto 1*: 
Ei muuteta toimintalogiikkaa; koodilohko aloittaa kokonaan uuden atomisen lohkon, joka jatkuu seuraavaan lohkoon asti. Koodilohkoa muokatessa lisätty sisältö tulee osaksi atomista lohkoa.

*Vaihtoehto 2*: 
Laajennetaan koodilohkon parsintaa siten, että atomisen lohkon sisään tulee myös kaikki koodilohkoa edeltävä sisältö edeltävään lohkoon asti, eli koodilohkot olisivat ikäänkuin inline-elementtejä muun tekstin/sisällön joukossa. Sisältöä joutunee lohkottamaan jonkun verran käsin käyttämällä \#- -merkintää.

*Vaihtoehto 3*: 
Samaistetaan erikoisalueiden (koodilohkojen ja pluginien) parsinta. Silloin takahipsuilla merkityistä osioista tehtäisiin poikkeuksetta oma lohkonsa (3+ takahipsua peräkkäin, vain ulommaisella tasolla olisi merkitystä lohkotuksen kannalta). Pluginin/koodilohkon ulkopuolinen sisältö ei olisi osa atomista lohkoa, vaan niistä tulisi omat lohkonsa.

Vaihtoehto 1 tietysti tarkoittaa, että käännösdokumenttien kanssa joutuu jatkossakin puljaamaan käsin.

Vaihtoehto 2 sisältää muutamia olennaisia ongelmakohtia: 
- vaatii erikoiskäsittelyä jälleen yhdelle erilliselle asialle -> aiheuttaa lisää laskentaa monimutkaisemman parsimisen ja tarkistusten vuoksi
- haittaa automaattista kääntämistä vielä lisää
- käyttäjiä pitää opettaa lohkottamaan sisältöä käsin (ei kovin käyttäjäystävällistä)

Itse suosisin vaihtoehtoa 3. Se selkeyttäisi toiminta- ja parsimislogiikkaa (vain yksi, selkeästi määritelty käsittely takahipsuilla rajatuille erikoisalueille). Lisäksi se mahdollistaa paremmin automaattikäännöksen normaaleille tekstialueille koodilohkon tms. häiritsemättä. Lohkoja tulisi dokumenttiin kokonaisuudessaan kenties hiukan enemmän.

**Comment by saviit** [comment]
Nähtävästi ~~~ -merkinnällä luotu koodilohko käyttäytyy jo nyt kuten ylempänä Vaihtoehto 2 on kuvattu, kts.<https://tim.jyu.fi/view/users/viitanen-sami/testikansio/atominen/lohkoutuminen2>. Käännöstä tehdessä aaltoviivat tosin muutetaan takahipsuiksi, mikä saattaa johtaa siihen, että jossain vaiheessa dokumentin elinkaarta alueet eivät kaikilta osin enää käyttääydy käyttäjän odottamalla tavalla ainakaan käännöksessä.

**Comment by saviit** [comment]
Päädyttiin vaihtoehtoon 2. Kielimääreellä varustettu koodilohko korjataan käyttäytymään samoin kuin 'tavallinen' koodilohko. Samassa pitää huomioida myös ~~~.

**Comment by vesal** [comment]
sius eikö mieluummin niin että kaikki paitsi plugin ei katkaise lohkoa

**Comment by saviit** [comment]
> sius eikö mieluummin niin että kaikki paitsi plugin ei katkaise lohkoa

Joo, sitä tuossa yritin sanoa.

**Comment by saviit** [comment]
Suljen tämän toteutettuna. ATomisten lohkojen poisto on omana korttinaan, ja se vaatii muutenkin vähän selvitystyötä ennen kuin sitä voi lähteä toteuttamaan.
