### ISSUE TITLE
Jos DrawIO komponentiin laittaa kuvan ja sitten muokkaa komponenttia tekstinä ei mitään näy. Sama jos kopioin komponentin.

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3242]
Jos esimerkieki ottaa tuon kuvan:

- <https://tim.jyu.fi/view/users/vesal/oma/talo/talo/paatylounas#puut>

ja pasteaa sen oletus DrawIO-komponenttiin ja sitten piirtää jotakin, niin
piirros ei mahdu vaan tulee skrollautuva komponentti.  Jos tämän JÄLKEEN
käy muuttamassa (Edit) vaikka

        height: 700

ja tallentaa piirroksen, niin mitään ei näy.  Jos tekee toisinpäin, niin näkyy.

Jos tuon em kuvan alla olevan DarwIO:-komponenin kopioi TIMin kautta ja pasteaa Content, niin 
silloinkaan ei näy mitään.

**Comment by vesal** [comment]
Itse asiassa hajoaa myös tuollainen missä on ensin laitettu korjaus ja muokattu onnistuneesti
jos laittaa uuden DrawIO-komponentin ja virkistää

**Comment by sijualle** [comment]
Mulla nuo kuvat tulee normaalisti, mutta firefoxin toiminta hidastuu. Aina sivun uudelleenlatauksessa, drawion tallennuksessa tai muokkauksen aloittamisessa menee joku 30 sekuntia ennen kuin selain alkaa vastaamaan. Mutta kuitenkin jos kopioin tuon kuvan drawioon, tallennan, ja käyn jälkeenpäin laittamassa tuon height 700 niin kuva latautuu, kunhan jaksaa välivaiheissa ja lopussa odotella. Tuleeko tuo kuva näkyviin jos toistat tuon uudestaan mutta odottelet lopuksi sen ilmestymistä?

Mutuna veikkaan että se hidastelee sen takia että jokaisessa latauksessa / muutoksessa siellä tulee iframen ja timin välissä viestintää siitä sisällöstä, ja siellä tuo iso kuva tukkii kaiken. Tuota voisi ehkä optimoida niin että se viestintä olisi vain ilmoitusta muutoksista eikä koko sisältöä. Siinä on tosin riskinä se että jos iframen sulkee tallentamatta niin silloin timille ei jää sitä viimeisen tilanteen kopiota niin kuin nyt jää.

**Comment by sijualle** [comment]
Tai no chromella näyttää luovuttavan kokonaan, kuva ei tule edes odottelulla. Firefoxilla tulee odottamisen jälkeen

**Comment by vesal** [comment]
Jännää kun se kuitenkin toimii tosi hyvin kun tekee sen 1. kerran.

**Comment by sijualle** [comment]
Tuolla iframen html:ssä oli rivi `Object.entries(data.c).length === 0` joka on hidas jos on pitkä vastaus (esim kuvadataa vastauksessa). Mutta tuo rivi on eliminoitavissa kun vähän refaktoroi. Nyt pitäisi tuon devsin drawion toimia nopeasti

**Comment by vesal** [comment]
OK, nyt on ihan käyttökelpoinen :-)

En tiedä voisiko tuollaisne kuvadatan käsitellä muuten jos sen ainoa rooli
on olla vähän kuin taustakuvana.  Komponenttiin sen varmaan saisi taustakuvana,
mutta miten sitten näkisi piirtää oikeaan kohtaan.

Nyt kai hieman turhaa on että se muuttuu tekstiksi tuossa.
Mutta eipä tuota enempää kannata miettiä.
