### ISSUE TITLE
Jotkin mp4-videot eivät näy Safarilla eikä Firefoxilla

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3243]
https://tim.jyu.fi/view/kurssit/jypeli/grafiikka/efektit

**Comment by dezhidki** [comment]
En saa toistettua kaikilla videoilla, esimerkiksi sivulla olevat luentovideot

https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/videoiden-hakemisto

kyllä näkyvät. Muutan toistaiseksi kortin otsikkoa, koska vaatii tutkinta.

Millä tavoin tuota Jypelin videota on tehty?

**Comment by dezhidki** [comment]
Firefoxin konsolin mukaan videon toisto epäonnistuu itse videon formaatin takia:

```
Mediaresurssin https://tim.jyu.fi/files/480365/output.mp4 purkaminen epäonnistui virheellä: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto __cdecl mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()(void) const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling
```

Tarkemman tiedon mukaan Firefox ja Safari käyttävät järjestelmän omaa H.254-koodaajaa, joka ei tue YUV444-värikoodausta: https://bugzilla.mozilla.org/show_bug.cgi?id=1368063

> While ffmpeg can decode them, neither windows WMF decoder nor Apple's one can.
> For coonsistency sake, we've disabled them on Linux too.
> 
> If you want to play yuv444 video, prefer a free codec such as vp9 for which we can provide decoder.

Chrome ilmeisesti tulee oman ffmpeg-pohjaisen koodaajan kanssa, joka osaa soittaa monipuolisempia videoita. 

Yllä olevan linkin perusteella avoin VP9-koodaus on täysin tuettu, eli MP4-videoiden kannattaa käyttää sitä. Väärin koodatut videot voi korjata käsin ffmpegilla komennolla

```
ffmpeg -i video.mp4 -c:v libvpx-vp9 -c:a aac output.mp4
```

Korjasin kortin esimerkkisivun videot tällä komennolla. Muuten suljen tämän kortin, koska ongelma ei liity itse TIMiin tai sen toimintoihin. Materiaalin omistajan kannattanee korjata muut videot, jos niitä on jossain muilla sivuilla.
