### ISSUE TITLE
Haku valintoihin valinta oletus vs nykyhakemisto

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3245]
Opiskelijat eivät osaa oikein muuttaa tuota haun hakemistoa.
Helpotus voisi olla jos olisi "linkit":  oletus (mikä toimii kuten nyt)
nykyhakmeisto (jolloin esim demodokumentissa ollessaan saisi haettua
helposti samassa hakemistorakenteessa olevista dokumenteista).

Linkin painaminen heittäisi hakemistokenttään vastaavan hakemiston polun.

**Comment by dezhidki** [comment]
En nyt saa ihan kiinni, mikä tuo "linkit" on. Siis tarkoitatko jotain tuollaista:

![image](https://user-images.githubusercontent.com/5202606/200165952-4547e5e2-aa7b-4c4d-b194-3d95c6306cf1.png)
(tehty nyt pikaisesti devtoolseilla)

tai siis miten tuota ajattelit?

**Comment by vesal** [comment]
Aika tarkaan noin.  ELi jos olen dokussa demo10 ja etsin vaikka aliohjelma ja haluaisin löytää missä
demoissa puhuttiin aliohjelmista, voisin painaan tuota `Current folder`.  Haastetaahn tuossa on
minusta sitten kun mennään toiseen hakemistoon ja ei huomata että siihen on jäänyt

      /kurssit/tie/ohj1/2022s/demot

ja taas hakee demot-hakemistosta.  Eli jos linkkiä painamalla on sama asia kuin hakemiston kirjoittamisella,
niin se jäänee siihen edit-kenttään kiinni?

**Comment by vesal** [comment]
Huomasin inohttavan käytettävyysongelman, en tiedä pitäisikö laittaa eri korttiin:

1. Yritän kirjoitata relevace-kohtaan 10 ja painan enter
2. Tulee -100

Edes kirjoittamalla 10 ja liikkumalla nuolilla en saa siihen 100,  koska nuolet ovatkin +/- skrolleja.

**Comment by dezhidki** [comment]
>  Haastetaahn tuossa on
minusta sitten kun mennään toiseen hakemistoon ja ei huomata että siihen on jäänyt

Tällä hetkellä hakukansio ei mene localStorageen, joten kun sivu vaihtuu, hakukansio menee takaisin oletukseksi.

**Comment by dezhidki** [comment]
> Huomasin inohttavan käytettävyysongelman, en tiedä pitäisikö laittaa eri korttiin

Oma kortti, mutta se johtuu tuosta typeahead-täydennyksestä. Sen voisi sinänsä varmaan ottaa pois relevanssin kohdalta.
