### ISSUE TITLE
Haun oletusrelevanssin nostaminen 10:iin

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3247]
Kannattaisiko haun oletusrelevanssiksi laittaa 10?
Jos oikein tulkitsen, se on nyt 1.

**Comment by dezhidki** [comment]
Joo, ja siis se tarkoittaa, että kaikki dokumentit, jossa relevanssi on 1 tai alle ei näytetä tuloksissa. 

Jos sen nostaa 10iin, niin kaikki perusdokumentit menee piiloon.

Periaatteessa jos oletukseksi laittaa 9, niin silloin kaikki alle 10:n laitetaan piiloon.
