### ISSUE TITLE
Muilla kuin Haka-tunnuksilla kirjautuminen piiloon napin taakse

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3266]
Tällä hetkellä sekä yleisimpiä tukipyyntöjä opiskelijoilta ovat:

"En pääse kirjautumaan TIMiin",
"En näe opettajan linkittämää TIM-dokumenttia", jne.,

jotka johtuvat siitä, että opiskelija/käyttäjä ei lukenut sisäänkirjautumisikkunan ohjeita, ja kirjautui itse tekemällään tunnuksella TIMiin ('olen unohtanut salasanani'-mekanismin kautta). Johdannaisvaikutuksena lisätyötä voi teettää esim. tunnusten yhdistämiset, jotta opintosuoritukset/pisteet tms. kohdistuvat oikeaan tunnukseen.

Juurisyynä (käyttäjän virheiden lisäksi) voi pitää sitä, että sisäänkirjautumisikkunan elementtien asettelu ohjaa voimakkaasti käyttämään vaihtoehtoista kirjautumistapaa (omat tunnukset): tunnusten syöttökentät ovat keskeisellä paikalla dialogissa Haka-kirjautumisen sijaan, ja Haka-kirjautumisen ohjeistus on heikosti huomiota herättävässä paikassa dilogiikkunan otsakepalkin alapuolella.

Kirjautumisdialogi pitäisi varmaan ajatuksella suunnitella uudestaan ennen pitkää (mm. uusia kirjautumistapoja silmälläpitäen), mutta nopeana välivaiheen ratkaisuna vaihtoehtoisen kirjautumisen elementit voisi piilottaa napin taakse, esimerkiksi jotenkin alla olevien kuvien tyyliin:

![Alkuperäinen login-dialogi](https://user-images.githubusercontent.com/46485327/203558269-afa05972-5b8e-42a7-86a0-b116d44bc683.png)
![Vaihtoehtoinen kirjautuminen piilotettu](https://user-images.githubusercontent.com/46485327/203558273-7e218c84-78c9-4f96-b16b-30763467e119.png)

**Comment by vesal** [comment]
Tää on niin kaksipiippuinen juttu.  Myöskää ei saisi tehdä "tavallisen"
käyttäjän elämää vaikeaksi.  Sitten tulee viestejä että en voi käyttää
TIMiä kun ei ole Haka-tunnuksia.

Kun tietäisi että käyttää omaa konetta, niin voisi olla keskustelevampi
kirjautuminen ja sitten kun on kerran kirjautunut, nii olisi localstoragessa
se kirjautumisen tyyppi ja seuravan kerran pääsisi vähemmällä valinnalla sisään.
Tämän ajatuksen taitaa pilata yhteiskäyttöiset kirjaston yms koneet.
JY-koneissahan esin kirjaudutaan sisään ja silloin on omat localstoraget, joten
niissä toimisi.

Ja jos jyu käyttäjä tekee oman salasanan, niin silloin Hakan pakottaminen
hidastaa kirjautumista.  Toki tuollaiset nimet kuin Haka-login ovat tyhmiä,
koska missään ei perusopiskelijalle ole opetettu mitä tuo tarkoittaa :-)

Vesa

**Comment by saviit** [comment]
Joo eihän tämä helppo ole, mutta ajattelisin tätä seuraavasti:

- kuinka paljon on Haka-käyttäjiä vs. omilla tunnuksilla käyttäjiä? Veikkaus että Haka-käyttäjiä enemmän nykyään.
- kuinka suuri vaiva omilla tunnuksilla kirjautuville on painaa nappia, kun se Haka-käyttäjiltäkin onnistuu (ainakin niiltä jotka osaavat kirjautua sisään...)
- jatkossa kun tulee uusia kirjautumistapoja niin ongelma vaan korostuu, ja joka tapauksessa asialle pitää jotain tehdä. Tässä olisi ainakin pienellä vaivalla tehtävä (ja helposti peruutettava) tapa kokeilla auttaako tämä nykyiseen ongelmaan vaiko pahentaa sitä.
