### ISSUE TITLE
ACE-editorin rivinumerolista menee ristiin vasemman yläkulman palkin kanssa

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3270]
ACE-editorissa oleva rivinumerolista (esim csPLugin) menee ristiin 
vasemman yläkulman palkin kanssa silloin kun sieltä ei ole mikään alasveto auki, ks esim:

  https://tim.jyu.fi/view/kurssit/tie/ohj1/2022s/tentti/20221202

**Comment by dezhidki** [comment]
Olisiko tuosta kuvakaappausta? En nyt saa kiini, mikä vasemman yläkulman palkki tulee cspluginissa.

**Comment by vesal** [comment]
![image](https://user-images.githubusercontent.com/826392/204230787-9a169a84-ca93-4bbf-b87f-29c1055d2217.png)

**Comment by vesal** [comment]
Olen saattanut itsekin nostaa joskus tuon rivinumerolistan z:aa, mutta siihen oli joku syy
että se jäi silloin jonkin muun alle. En enää muista minkä...
