### ISSUE TITLE
AB: Jos menee henkilön kohdalle jolla on vain yksi yliajalla oleva vastaus, niin vastauksena näkyy edellinen näkyvissä ollut vastaus

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3278]
Esimerkiksi:

https://tim.jyu.fi/teacher/kurssit/tie/ohj1/2022s/tentti/20221202#itsetext

vastaaja numero 105.  Tuo toimii jos ei ole ruksia Näytä vain validit vastaukset, mutta
jos ruksi on päällä, niin ko henkilön kohdalla mitään ei tapahdu ja siksi vastauksia
selaava luulee kohdalla olevaa vastausta (joka voi olla kenen vaan kun tulee sopivaa kautta)
tuon henkilön vastaukseksi.

**Comment by sijualle** [comment]
Nyt on korjattu. Jos tulee tilanne jossa henkilöllä ei olekaan valideja vastauksia niin tehtävässä näytetään vastaamatonta tehtävää, sellaisena kun vastaaja sen itse näkisi, ja lisäksi huomautetaan että käyttäjällä ei ole valideja vastauksia. 
#3288
