### ISSUE TITLE
Ripgrep käyttämään automaattista syntaksitunnistusta TIM-haussa

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3282]
Refaktoroidussa TIM-haun palvelinkoodissa käytettävä ripgrep mahdollistaa PCRE2-syntaksin mukaisten regular expressioneiden käyttämisen, ja tämä on palvelimen puolella jo huomioitu (tosin toistaiseksi kommentoituna). <s>Käyttöliittymän puolelle voisi laittaa Regex-valinnan alapuolelle vaihtoehdon tälle myös.</s>

**Comment by saviit** [comment]
PCRE2:lla saa tehtyä rekursiivisia regexpejä, mitkä ei onnistu tuolla tavallisella. Ja Denisin kanssa katsottiin että ripgrepin saa itse asiassa automaattimoodiin, jolloin se käyttää annetun syntaksin mukaista versiota.

**Comment by vesal** [comment]
> PCRE2:lla saa tehtyä rekursiivisia regexpejä, mitkä ei onnistu tuolla tavallisella. Ja Denisin kanssa katsottiin
> että ripgrepin saa itse asiassa automaattimoodiin, jolloin se käyttää annetun syntaksin mukaista versiota.

Olisikos mitään järkeä ajatella sellaista Googlea matkivaa TIM-syntaksia,
jossa voisi sanoa ihan vaan

       kissa koira

ja se etsii dokuja, joissa on kissa ja koira (kuinka kaukana???).
Simppelein olisi että kääntää tuon vastaavaksi regexpiksi

Ja sitten joku

       kissa OR koira

kääntyisi

       (kissa|koira)

vai minkälaisia ne käyttäjtä Googleen kirjoittavat?

**Comment by saviit** [comment]
Tämä kortti toteutettu nyt haarassa #3257
