### ISSUE TITLE
#nimet ovat korkeammalla Z k uin users with answers

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3284]
Esim:

https://tim.jyu.fi/teacher/kurssit/tie/ohj1/2022s/eteneminen

ja sitten laajempaan menuun.  Silloin #-nimet lohkojen päissä tulevat users with answers päälle.

**Comment by saviit** [comment]
En saa tätä toistettua lohkoankkureiden (#) kanssa, sen sijaan Velp badge (kommenttilätkän näköinen, mutta velpeille) saa suuremman z-indeksin kuin userlist:
![userlist-zindex](https://user-images.githubusercontent.com/46485327/206389540-b9f9c548-ed4c-4933-996f-7449ed6f5ad1.png)


Korjaan tämän nyt nostamalla .right-side-fixed -tyylin z-indeksiä. Userlistin oman tyylin z-indeksin asettaminen ei valitettavasti korjaa tätä, sillä tuo .right.side.fixed ajaa sen yli.

**Comment by saviit** [comment]
Tämä korjattu nyt PR:ssä #3285

**Comment by vesal** [comment]
![image](https://user-images.githubusercontent.com/826392/206399592-45e7a837-7fc8-41f7-81af-41247a88b62a.png)
