### ISSUE TITLE
csplugin ohjelman tuloste turhan himmeä

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3286]
Katson tuossa videota NumPy-pikakurssista ja siinä ajetaan noita Python ohjelmia.

Videolla on vaikea näköjään erottaa mustalla pohjalla olevia harmaita tulosteita, eli varmaan
tuota tulosteen harmaata kannattaa viedä oletuksena aika paljon enemmän valkoista kohti.

**Comment by dezhidki** [comment]
Olisiko joku mallia

https://tim.jyu.fi/view/tim/Eri-ohjelmointikielia?themes=/styles/user/better-console-font

Väri otettu samaksi kuin on bash shellissa.

**Comment by vesal** [comment]
Alempi on Chrome ja ylempi FireFox, siinä ihmeellisen sotkuinen (ja se alkuperäinen himmeä)

![image](https://user-images.githubusercontent.com/826392/206736784-bc3fd1b6-987b-41f3-8f7c-8c7a8b925cc6.png)

**Comment by vesal** [comment]
Mutta selkeästi kuitenkin paremmin luettavissa kuin videolla:

https://m3.jyu.fi/jyumv/ohjelmat/it/tietotekniikan-laitos/tiep140/2022/recording-27-03-2022-23.15/view

polkuavain: tiep140_2022

**Comment by dezhidki** [comment]
Onko tuo polkuavain julkinen? GitHub on kuitenkin avoin kaikille.

**Comment by vesal** [comment]
Se on tuolla julkisella sivulla:

  https://tim.jyu.fi/view/kurssit/tie/tiep140/2022s/home

**Comment by dezhidki** [comment]
Okei :)

Säädin hieman fontteja lisää, olisiko nyt sellainen, että voisi ottaa oletukseksi?

**Comment by dezhidki** [comment]
Joo, nyt ainakin itselläni kummallakin näkyy ihan hyvin:

![image](https://user-images.githubusercontent.com/5202606/206740326-6a4716c7-9b2c-4cfa-9a0b-a17329687c36.png)


(vasen on Chrome, oikea Firefox). Toki kuvakaappauksilla niitä on vähän kehnoa vertailla, koska eri selaimilla on hieman erilainen renderöinti. Myös oman koneen asetukset voivat vaikuttaa siihen, miten fontit piirretään.

Mutta otan tuon nykyisen version sitten, se näyttää olevan hyvä kompromissi kaikilla laitteilla. Jos haluaisi parempaa, pitäisi ottaa käyttöön jotkin ulkoiset fontit.
