### ISSUE TITLE
$\LaTeX$ ei toimi jos on math_type: svg

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3301]
$\LaTeX$ ei toimi jos on math_type: svg

Toimii vain MathJaxissa.

**Comment by dezhidki** [comment]
Ei ole sinänsä mikään bugi, MathJaxin (ja KaTeXin) syntaksi poikkeaa paikoin virallisesta LaTeX + AMSMath -syntaksista. Jos haluaa kirjoitustavan, joka toimii sekä MathJax + virallinen LaTeX, pitää kirjoittaa `$\text{\LaTeX}$`.

Näitä poikkeuksia on sen verran paljon, että niille ei nyt oikein voi mitään (eikä niitä nyt kannata lähteä kaikkia tutkimaan, se on vähän turhan suuri työ). Parempi vaan tapauskohtaisesti korjata, kun kytkee `math_type: svg`.

**Comment by dezhidki** [comment]
Lisäsin tästä selityksen ohjeisiin: <https://tim.jyu.fi/view/tim/TIM-ohjeet#kaavasvg>
