### ISSUE TITLE
Kalenterin Massamuokkauksen virheen parempi ilmoitus

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3309]
Nyt jos pastean massamuokkaukseen käsin tehdyn JSONin, saatan saada:

       JSONia ei voitu käsitellä: SyntaxError: Bad control character in string literal in JSON at position 3896

Tuosta paikan 3896 ympäriltä voisi näyttää hieman tuota koodia, niin saisi selville missä
kohti suurinpiirtein on vika.

**Comment by dezhidki** [comment]
Siirrän toistaiseksi osaksi #2646
