### ISSUE TITLE
OpenAI API höytykäyttöön

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3326]
Joku voisi esim graduna tutkia saataisiiinko tuosta:
   
https://beta.openai.com/docs/api-reference/introduction

jotakin opetuksessa hyödynnettävää TIMiin.

**Comment by dezhidki** [comment]
Pitäiskö tällaiset graduaiheet laittaa ehkä vaan johonkin suoraan TIMiin eikä GitHubiin kehityskortiksi. Etenkin kun tämä on nyt sen verran epämääräinen vielä.

**Comment by vesal** [comment]
Ihan miten vaan kun määritellään mitä minnekin.  Voisihan TIMissä
olla vastaava hakemisto kui Proj aiheille niin
TIM-graduille.

Vesa

**Comment by dezhidki** [comment]
Siirsin graduehdotuksen omaan dokumenttiin: <https://tim.jyu.fi/view/tim/tutkimus/graduehdotuksia/chatgpt-hyotykaytto>

Muut TIMiin liittyvät pro gradu -tutkielman aiheet voi laittaa samaan kansioon.
