### ISSUE TITLE
Parsons tehtävä antamaan kääntäjälle vain rajaviivan yläpuoliset lauseet

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3342]
Nyt Parsons tehtävään voi laittaa 

     parsonsmaxcheck: 4

jolloin tulee rajaviiva jonka yläpuolella voi olla 4 riviä.  Tästä pitäisi saada versio, missä
kääntäjä saisi käyttöönsä vain nuo viivan yläpuoliset.  Periaattessa onnistuisi preprogrammilla,
mutta silloin se "rikottu" versio tallentuisi ja ylimääräisiä ei ole enää seuraavalla kertaa käytössä
(tai postprogrammin pitäisi osata korjata ongelma).

Lisäksi pitäisi saada optio jossa tuo rajaviiva kelluu vapaasti tai ainakin voisi sanoa

    parsonsmaxcheck: [2, 7]

Todennäköisesti helpoin toteutus olisi vain lisätä yleinen csPlugin attribuutti jolla voidaan
"tuhota" vastauksesta tietyn regepx ehdon jälkeinen osa kokonaan pois.  Silloin jos tässä parsontehtävssä laittaisin kommentin

        # Käyttämättömät lauseet alapuolelle

ja saisi sen jotenkin väritetty ja sitten csPluginin käsittelyvaiheessa regExpillä leikattu loput
pois, niin osa tulisi hoidettua.  

Myös Parsonin väritys vastauksen jälkeen pitäisi tässä käyttötapauksessa voida attribuutilla estää.

**Comment by dezhidki** [comment]
Varmistuksena: onko tämä yleistä ehdotusta, tai ihan valintakokeisiin tarkoitettu ominaisuus?

**Comment by vesal** [comment]
Yleinen, mutta valintakoe aiheuttaa tarpeen, siksi en tehnyt salaista mutta en maininnut vk

**Comment by dezhidki** [comment]
Mutta siis jos tämä on jotain, mitä pitää ennen valintakokeita saada aikaan, niin voin laittaa `valintakoe`-label, niin nostetaan prioriteettia.

**Comment by vesal** [comment]
Jos päättävät käyttää tätä tehtävätyyppiä, niin silloin pitää prioriteettia
nostaa. Ja haluavat ylimääräisiä lauseita.

**Comment by vesal** [comment]
Tehty tuossa:  https://github.com/TIM-JYU/TIM/pull/3344
