### ISSUE TITLE
AnswerBrowser: Ctrl+nuoli vaihtaa vastaajaa

### ISSUE THREAD

**Issue by ajlakanen** [TIM-JYU/TIM#3376]
Näppäinoikotiet Ctrl+nuoli vasen/nuoli oikea on kaikissa minun tuntemissani editoireissa (pl. ehkä Vim ja Emacs) tekstissä liikkumista varten. 

AnswerBrowserissa se kuitenkin vaihtaa käyttäjää, mikä on erittäin hämmentävää silloin, kun haluaa tutkia opiskelijan koodia ja tehdä siihen muutoksia (esim. opiskelija kysyy missä hänen koodissaan on vika ja silloin on helpointa tehdä pikkumuutoksia hänen koodiinsa).

Ehdotan että tuo näppäinoikotie vaihdetaan AnswerBrowserissa johonkin muuhun tai poistetaan kokonaan.

**Comment by vesal** [comment]
Ideana on ollut että ylä/alanuolilla on jopea selata vastaajia ja sivuttain
heidän vastauksiaan.

**Comment by vesal** [comment]
Muuten Higlight editorissa ei hyppele, vaan editori ottaa ne painikkeet.
Eli minusta on oikeastaan ihan hyvä noin, voi valita sen kumpaako käytöstä
haluaa.

**Comment by ajlakanen** [comment]
Ahaa, en tiennyt tuota. Pitääpä muistaa laittaa Highlight päälle muokatessa. Suljen tiketin.
