### ISSUE TITLE
GroupJoin: Automaattinen suorittaminen URL-parametrista

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3379]
GroupJoin pitäisi pystyä suorittaa automaattisesti URL-parametrilla. Yksinkertaisin voisi olla `selfJoin=true`, joka ajaa sivulla olevat liittymispainikkeet.

**Comment by vesal** [comment]
Pitäisikö kuitenkin olla sen selfJoin-komponentin nimi, jolloin sellaisella sivulla, jolla olisi vaihtoehtona liittyä
x tai y ryhmään, voisi jo URLilla valita mihin liitytään.  Ja mahdollisesti lista jolloin x,  y z tapauksessa
voisi voisi sanoa selfJoin=x,y jossakin linkissa ja toisessa selfJoin=,yz

**Comment by dezhidki** [comment]
Joo, laitan vaikka niin
