### ISSUE TITLE
Referrer-headerin arvoja makroksi

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3380]
Käyttöesimerkki: Korpissa on linkki TIM-sivulle. TIM-sivulla pitää näyttää kurssille liittymispainikkeen vain, jos käyttäjä avasi linkin Korpin kautta. Korpissa ei ole mahdollisuutta asettaa henkilökohtaista arvoa URLiin, vaan ainoa tieto saadaan Referrer-headerista.

Lisätään TIMiin makro `referrers`, joka sisältää N viimeisintä Referrer-arvoa. Historia tulee pitää, koska käyttäjä voi välillä esim. kirjautua sisään, mikä muuttaa viimeisintä Referreria.

**Comment by vesal** [comment]
Pystyisikö TIMin itse "väärentämään" referer tiedot niin, että krijautumisessa
käynnin jälkeen olisi edelleen alkuperäinen referer?
