### ISSUE TITLE
Viitealue käännettävässä dokumentissa ei toimi

### ISSUE THREAD

**Issue by sijualle** [TIM-JYU/TIM#3388]
Jos alueen liittää viitteenä toiseen dokumenttiin, ja tästä toisesta dokumentista tekee käännöksen, tuota viitattua aluetta ei pysty kääntämään. Lisäksi jos aluetta yrittää muokata käännösdokumentissa, se tekee käännösdokumenttiin ylimääräisiä kopioita alueen sisäisistä kappaleista

**Comment by saviit** [comment]
Korjattu/korjataan PR:ssä #3448
