### ISSUE TITLE
Viitelohkot käännetyissä dokumenteissa eivät viittaa lähteen käännöksiin

### ISSUE THREAD

**Issue by sijualle** [TIM-JYU/TIM#3405]
Jos on seuraava tilanne:

1. Dokumentti A:sta tehdään käännös
2. Dokumentti B ottaa viitteinä lohkoja A:sta
3. Dokumentti B:stä tehdään käännös samalle kielelle kuin A aiemmin
-> Dokumentti B:n käännösversiossa viitelohkojen pitäisi oletuksena tulla A:n käännösversiosta

Mutta tällä hetkellä B:n käännösversiossa viitelohkot osoittavat A:n alkuperäisiin, kääntämättömiin lohkoihin. 
Tuon pitäisi toimia myös riippumatta siitä tehdäänkö vaiheita 1/2/3 eri järjestyksessä

#3388 liittyy

**Comment by saviit** [comment]
Tätä on osittain selvitelty myös korteissa #3249 ja #3231. Tämän ratkaisemiseksi täytyy huomioida myös atomilohkotuksen poisto (kortti #3235).

**Comment by saviit** [comment]
Näköjään koko dokumenttia kääntäessä kutsutaan
https://github.com/TIM-JYU/TIM/blob/19cb50c549a060213db51be0c670f1d8d445f475/timApp/document/translation/routes.py#L100-L105
joka ei ilmeisesti hae viitelohkoja:
https://github.com/TIM-JYU/TIM/blob/19cb50c549a060213db51be0c670f1d8d445f475/timApp/document/document.py#L1082-L1095

Tämä siis saattaisi ratketa kutsumalla tuota `get_derefenced_paragraphs`. 

Itse asiassa tässä tulee sellainen ongelma, että nuo alkuperäisen dokumentin viitelohkot muunnetaan käännöksessä käännöslohkoiksi. Viitelohkoja ei periaatteessa saisi muuttaa mitenkään tuota käännöstä varten, koska nehän ovat tarkkaan ottaen sitaatteja alkuperäisdokumentista (joku voi joskus toivoa/vaatia, että noihin myös merkitään sitaatin lähde automaattisesti lukijan näkyville...). 

Viitealueiden (kts. #3388 ) kanssa tämä menee todennäköisesti hankalammaksi.
