### ISSUE TITLE
Toive (24.5. mennessä): csPluginille attribuutti joka näyttää koodin heti

### ISSUE THREAD

**Issue by saviit** [TIM-JYU/TIM#3409]
A-J toivoo 24.5.23 pidettävään kokeeseen mennessä csPluginille attribuuttia, jolla plugin näyttäisi ohjelman koodin heti kun plugin ladataan:

- toimii kuin nykyinen showCodeOn, mutta...
- ...koodi ladataan heti, sen sijaan että joutusi painamaan nappia/linkkiä
- voisi olla vaikka showCodeByDefault tms.

Onko tässä mitään erikoisempaa huomioitavaa?

**Comment by dezhidki** [comment]
`viewCode: true` taitaa tehdä jo tuon:

<https://tim.jyu.fi/view/tim/ohjeita/csPlugin#attributes>
<https://tim.jyu.fi/view/users/dezhidki/snipetit/snip-viewcode>

**Comment by saviit** [comment]
Okei, enpä tuota huomannut. Suljen siis tämän kortin tarpeettomana.
