### ISSUE TITLE
Haluaisin Teacher-näkymässä nähdä onko opiskelija lukinnut vastauksensa ja katsonut mallivastauksen

### ISSUE THREAD

**Issue by ajlakanen** [TIM-JYU/TIM#3417]

**Comment by dezhidki** [comment]
Liittyy korttiin #2638

**Comment by sijualle** [comment]
Eilen mergettiin päivitys (#3497) joka korvaa vanhan mallivastausten poistodialogin taulukolla josta voi kunnolla selata ketkä kaikki ovat tehtävän lukinneet. Tuo löytyy siis jokaisen mallivastauksella lukittavan tehtävän kohdalla answerbrowserista "Hallitse mallivastausten lukituksia"-linkin alta jos on teacher-oikeus

![kuva](https://github.com/TIM-JYU/TIM/assets/63715895/6645ea6d-153a-4cc7-862a-d59f499b5803)
