### ISSUE TITLE
Jos postprogram kaatuu vastauksen tallentamisessa, koko vastaus ei tallennu

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3436]
Jos postprogram on virheellinen (tai muuten kaatuu), niin tehtävän vastaus ei tallennu.

Logiikka pitäisi muuttaa siten, että postprogrammin kaatuessa vastaus tallenetaan oletuksena epävalidina. Lisäksi lisätään attribuutti, jolla epäonnistunut vastaus voidaan tallentaa validina. 
Lopuksi vielä virheviesti pitää tarkentaa.

**Comment by saviit** [comment]
Tästä myös kortti #3371
