### ISSUE TITLE
Asiakirjan kieli automaattisesti määriteltyihin makroihin

### ISSUE THREAD

**Issue by Tuplanolla** [TIM-JYU/TIM#3452]
Olisi kätevää, jos useamman käännöksen kesken jaetut johdantoasiakirjat tai
makrot voisi mukauttaa niitä käyttävien asiakirjojen kieliin.

**Comment by dezhidki** [comment]
Olin juuri eilen katsomassa noita automaattisia makroja ja ajattelin lisätä tuon saman :)
Lisään kohtapuolin.

**Comment by dezhidki** [comment]
Nyt on lisätty makro `doclang`, joka antaa dokumentin kielikoodin (tai None jos ei ole asetettu). Esimerkki: <https://tim.jyu.fi/view/users/dezhidki/snipetit/snip-doclang/fi>

Olisiko tämä, mitä hait?

**Comment by Tuplanolla** [comment]
On hyvä!
