### ISSUE TITLE
Luentokysmys jos on liian iso, niin sen yläpalkkiin ei pääse kiinni

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3483]
jos luentokysymyksestä tulee liian korkea, niin otsikkopalkkiin ei pääse käsiksi eikä paikkaa voi muuttaa,
ks:

 https://tim.jyu.fi/view/kurssit/tie/ohj1/2023s/luennot/luento07

**Comment by dezhidki** [comment]
Duplikaatti: https://github.com/TIM-JYU/TIM/issues/3184
