### ISSUE TITLE
Ruksit häviää cbCountFieldistä

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3492]
Opiskelijat sanoivat että tuonne:

https://tim.jyu.fi/teacher/kurssit/tie/ohj1/2023s/demot/demo5

tehty ruksi häviää kun seuraavan kerran tulee sivulle.

**Comment by dezhidki** [comment]
Onko jotain tiettyjä opiskelijoita (voi laittaa listan meidän postiin: tim@jyu.fi)? En saanut toistettua muuten että ruksin tallentuminen hidastuu countin kasvaessa. Johtuu siitä, että tällä hetkellä talentaessa käyttäjälle palautetaan uusi count.

Eli voi olla mahdollista että opiskelijat eivät maltanneet odottaa tallentumista.

**Comment by dezhidki** [comment]
En saanut keneltäkään. Testaan nyt jollakin tunnuksella.

**Comment by dezhidki** [comment]
Testasin muutamalla. Ruksit näkyvät ja tallentuvat, mutta tosiaankin tallennus hidastuu sen mukaan, mitä enemmän ruksijoita on. Esimerkiksi "Katson demonpalautuksen videolta" -ruksin tallentaessa menee jopa 4 s, eli aika paljon aikaa.

Eli ihan ekaksi koitan korjata tuota latausta

**Comment by juuso-turunen** [comment]
Minulla on sama ongelma. Ks. video: https://clipchamp.com/watch/v5MOa8spwcm

Ainoastaan "Katson demonpalautuksen videolta"-ruksi menee checkatuksi sivun päivittämisen jälkeen, vaikka olisi valinnut kaikki ennen sivun päivittämistä. Ongelman olen toistaiseksi nähnyt vain demo-sivuilla. Esimerkiksi luento-sivuilla vastaavanlaiset valintapainikkeet toimivat odotetusti (kuva alla)


![image](https://github.com/TIM-JYU/TIM/assets/44379448/fb4fdafe-5edf-4582-84c4-8c71db7dc6a3)
(https://tim.jyu.fi/view/kurssit/tie/ohj1/2023s/luennot/luento12)
Kuvassa tilanne sivun päivittämisen jälkeen.

**Comment by juuso-turunen** [comment]
En saa enää ongelmaa toistettua, eli nyt toimii odotetulla tavalla.

Hienoa työtä!

**Comment by dezhidki** [comment]
Tämä nyt korjattu lopullisesti: 0b1f49ad
