### ISSUE TITLE
Kvanttisimu rikkoo TIMin 

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3523]
Tein seuraavan 

https://tim.jyu.fi/view/kurssit/tie/kvanttiaakkoset/spessu/alpha#tehtava27

Vaihdoin tuohon 

         nQubits: 3    tilalle
         nQubits: 4

ja sen jälkeen sivulla ei voi enää muokata mitään

**Comment by saviit** [comment]
Tuossa jos muuttaa tuota `nQubits` niin pitää silloin myös alustaa vastaava määrä siellä `qubits`-attribuutissa. Toki kummankaan muuttaminen ei saisi rikkoa sivua.

**Comment by dezhidki** [comment]
CC @juanrein katsotko tuota kun ehdit
