### ISSUE TITLE
fieldmacros

### ISSUE THREAD

**Issue by vesal** [TIM-JYU/TIM#3525]
Käyttötapaus:

  https://tim.jyu.fi/view/kurssit/it/hankinnat/julkisten-hankintojen-perusteet/osa1

Tuonne jos haluttaisiin menuun Osat-linkin alle tyyliin

      Osa 1, pisteet 3/5
      Osa 2, pisteet 4/5

niin tuo voisi yleiskäyttöisimmin onnistua seuraavasti: 

1. Preambleen asetuksiin kohta (docid 1234 olisi vaikkapa tuo pisteet-doku)

             fieldmacros:
                 1234.osa1: osa1
                 1234.osa2: osa2
                  ...

2. tuon jälkeen olisi käytössä käyttäjän osalta makrot osa1, osa2, ...
3. menuun voisi kirjoittaa 

                - Osa 1, pisteet %%osa1%%/5
                - Osa 2, pisteet %%osa2%%/5
4. Käytännössä luonnollisesti tuo ´/5`tulisi myös makrotaulukosta johon olisi lueteltu osien maksimit

Tuolla samalla saattaisi saada myös sen Ohj1:n demo11 mallin mukaisen otsikon jos tuo fieldmacros noudattaisi
kaikkia fiedien haun sääntöjä (mm ´.points´).  

Tosin kiireellisyyttä tuon hankinta-jutun osalta pudottaa se, että kullekin sivulle voi suoraan lainata
pisteitä-dokusta sen yhteispistemäärä taulukon (kunhan sen sinen saa laitettua).  Ja se taas vaatisi
yksilön kohdalta nopeampaa päivitystä kuin kerran tuntiin.

Tosin vaatii refresh että päivittyy.

Ylimääräinen haaste:  Mitä tehdään teacher-näkymässä?  Olisko kuitenkin silloinkin vain userin mukainen haku?

**Comment by dezhidki** [comment]
Eikös tuo ole sama kuin https://github.com/TIM-JYU/TIM/issues/3518 joka juuri muutama päivä sitten kyseltiin? Jos ovat samat jutut, niin mielellään yhdistän nämä kummatkin kortit niin ei tule turhia duplikaatteja.

**Comment by vesal** [comment]
Ei ihan, mutta sitä vanhaa voisi osin tehdä tällä.  Siinä #3518idea oli että tietoa haettaisiin saman dokun fieldeistä suoraanjs:llä jollon tulos olisi reaaliaikainen eikä rasittaisi palvelinta.Tässä palvelin tekisi kaiken työn ja tulos ei ole reaaliaikainen.VesaDenis Zhidkikh ***@***.***> kirjoitti 17.11.2023 kello 20.11:﻿
Eikös tuo ole sama kuin #3518 joka juuri muutama päivä sitten kyseltiin? Jos ovat samat jutut, niin mielellään yhdistän nämä kummatkin kortit niin ei tule turhia duplikaatteja.
