### ISSUE TITLE
Tulosteen kokorajoitetta ei ole dokumentoitu

### ISSUE THREAD

**Issue by Tuplanolla** [TIM-JYU/TIM#3601]
Kun ajan käyttäjän ohjelmia `csPlugin`illa,
ohjelmien tuloste katkeaa 20000 tavuun.
Tätä rajoitetta ei ole dokumentoitu, ja
se hajottaa toisinaan omat protokollani
ajettavien ohjelmien ja JavaScriptin välillä.

**Comment by dezhidki** [comment]
Hei, pahoittelen vastausviivettä!

Tuo ei ole ehkä selkeästi dokumentoitu, mutta csPluginissa stdout on oletuksena rajattu 20000 merkkiin. Rajan saa nostettua `maxConsole`-attribuutilla:

```yaml
maxConsole: 900000
```

Kyseinen asetus on mainittu csPluginin ohjeissa: <https://tim.jyu.fi/view/tim/ohjeita/csPlugin#YghFwbuxHUEj>.

Lisäsin nyt pluginin ohjeisiin maininnan resursseista:

https://tim.jyu.fi/view/tim/ohjeita/csPlugin#resurssien-rajoittaminen

Tämä lienee ratkaista tämän kysymyksen. Kerro, jos on vielä muita ongelmia.
