### ISSUE TITLE
TableForm: Filteröinnin vertailuoperaattorit toimimaan merkkijonoille (akkostuva järjestys)

### ISSUE THREAD

**Issue by dezhidki** [TIM-JYU/TIM#3700]
TableFormin ja TimTablen filtteroinnin vertailuoperaattorit (`=`, `<`, `>` yms) voisi toimia myös puhtaille merkkijonoille. Silloin järjestystä määrää leksikografinen järjestys (eli käytännössä "aakkosjärjestys"). 

Tämä helpottaisi esimerkiksi ISO-muotoisten päivämäärien suodattamisen, sillä ne on suunniteltu aakkosjärjestyksen kanssa toimivaksi.

Käytännössä tämä voinee toteuttaa käyttäen JS:n sisäänrakennettua [`localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) -funktiota.

**Comment by vesal** [comment]
Operaattorit > < >= <= == toimivat kyllä merkkijonoille, mutta jostakin syystä ei pvm
